### ISSUE TITLE
Serving static files

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/names#107]
Currently, the clojure app is attempting to serve both the API and static resources.

@sibyl229  Is it correct that the static assets are not served by the app when you're developing via `yarn run start`?

It makes the compojure-api routing configuration more complex than's desirable....
I'm thinking we should [delegate the serving][1] of static assets to the nginx proxy].

This would nullify the #104 and similar issues regarding serving the client assets.

[1]: https://davidojeda.mx/blog/2018/01/11/extend-nginx-config-on-aws-elasticbeanstalk

**Comment by mgrbyte** [comment]
Merge of #104 has caused tests to fail, and content-type is incorrect for all API calls.

**Comment by sibyl229** [comment]
I see! Yeah, when you run the webpackDevServer, it serves all the static file from memory, and proxies all the calls that it doesn't know how to respond to backend. 

I wonder if changing the order of the middleware would solve the problem. If it can, then it avoids the complexity of having to run nginx or webpackDevServer to have a site without broken images. But in any case, I'm okay with having nginx serving the static files, if we need or if it makes things easier for us.

**Comment by mgrbyte** [comment]
Think we'll see how we get on with things as they are; can always do it later if required.

**Comment by mgrbyte** [comment]
Closing, will re-open/create new if needed.
