### ISSUE TITLE
commiting yarn files

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/names#120]
Should `yarn.lock` be versioned or added to .gitignore?
I recently upgraded `yarn` (via `apt`  on my ubuntu machine) to `0.15.0-1`.
When running `yarn install`, this seemed to resolve more deps and udpate the yarn.lock file, which now shows up unchanged in `git status`.

**Comment by sibyl229** [comment]
Hi @mgrbyte , yarn.lock should be committed to git. It tracks the exact versions of all the npm module dependencies installed, so there is a way to install the exact same dependencies if anything goes wrong. 

yarn 0.15 seems to be of an older version though. The current stable version is 1.10.1. If you installed it through apt-get, maybe it doesn't have the latest version. Here are the instructions for installing yarn on Ubuntu: https://yarnpkg.com/en/docs/install#debian-stable

If you still notice changes in the yarn.lock file after upgrading yarn, feel free to commit it. If there is any issue, we can always revert back.

**Comment by mgrbyte** [comment]
Nah am on 1.10.1 after all, misread output of `apt-cache show`
