### ISSUE TITLE
Event Notifications

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/names#149]
Possibly notify a list of subscribers when an event occurs.

See [this](https://github.com/WormBase/website/issues/6830 ) for motivation

If we did this, the UI could have a feature (possibly on a users' "profile" page (new) that would list all events and allow them to check against the ones they want to subscribe (merges, splits, created etc),
perhaps on a per entity type and/or species level.

**Comment by sibyl229** [comment]
Hi @mgrbyte 

Having the UI for subscribing and unsubscribing should be doable. 

Would it be necessary for the UI to show a list of events that the user subscribe to, like how https://github.com/notifications does it?

**Comment by mgrbyte** [comment]
I imagine that'd be useful (if we implemented this)

**Comment by sibyl229** [comment]
@mgrbyte here is a mock up while I'm at it: https://www.figma.com/file/FGYDp7mes6Fc67NxvMBFuRsJ/Untitled?node-id=0%3A1

I'm happy to wait until your other more urgent work is done before we work on this one, If we implement this feature.

**Comment by mluypaert** [comment]
In meeting with Magdalena, we decided to close this issue because we decided not to implement this.
