### ISSUE TITLE
GET Gene pattern matches unexpected entries

### ISSUE THREAD

**Issue by gw3** [WormBase/names#167]
A GET search for 
https://names.wormbase.org/api/gene/?pattern=Bma-cutl-12
pulls out:
         'matches' => [
                         {
                           'gene/id' => 'WBGene00228910',
                           'gene/sequence-name' => 'Bm8649'
                         },
                         {
                           'gene/id' => 'WBGene00231346',
                           'gene/sequence-name' => 'Bm11085'
                         },
                         {
                           'gene/id' => 'WBGene00221002',
                           'gene/sequence-name' => 'Bm741'
                         }
                       ]

**Comment by mgrbyte** [comment]
This will be fixed in the next release.
They match because the cgc-names match (but are not returned by the currently released version):
```json
{
  "matches": [
    {
      "gene/id": "WBGene00228910",
      "gene/cgc-name": "Bma-cutl-12.3",
      "gene/sequence-name": "Bm8649"
    },
    {
      "gene/id": "WBGene00231346",
      "gene/cgc-name": "Bma-cutl-12.1",
      "gene/sequence-name": "Bm11085"
    },
    {
      "gene/id": "WBGene00221002",
      "gene/cgc-name": "Bma-cutl-12.2",
      "gene/sequence-name": "Bm741"
    }
  ]
}
```
