### ISSUE TITLE
Getting failure when doing an update

### ISSUE THREAD

**Issue by gw3** [WormBase/names#177]
curl -X PUT -H "Authorization: Token $TOKEN" -H "content-type: application/json" --data '{"data": {"gene/biotype": "biotype/transcript", "gene/species": "Caenorhabditis elegans"}, "prov": {"provenance/why": "Testing"}}' -v https://names.wormbase.org/api/gene/ZK1320.15

"-- Spec failed --------------------

  {:prov ..., :data {:gene/species ..., :gene/biotype ...}}
                                        ^^^^^^^^^^^^^

should be one of: :gene/cgc-name, :gene/id, :gene/species, :gene/status

-- Relevant specs -------

:wormbase.specs.gene/uncloned:
  (spec-tools.core/spec
   {:spec
    (spec-tools.core/merge
     (clojure.spec.alpha/keys
      :req
      [:gene/species :gene/cgc-name]
      :opt
      [:gene/status])
     (clojure.spec.alpha/map-of
      #{:gene/cgc-name :gene/species :gene/status :gene/id}
      clojure.core/any?)),
    :type :map,
    :keys #{:gene/cgc-name :gene/species :gene/status},
    :keys/req #{:gene/cgc-name :gene/species},
    :keys/opt #{:gene/status}})
:$spec31083/data:
  (spec-tools.core/spec
   {:spec
    (spec-tools.core/spec
     {:spec (clojure.spec.alpha/spec :wormbase.specs.gene/new),
      :type nil}),
    :type nil})

-- Spec failed --------------------

  {:prov ...,
   :data {:gene/species ..., :gene/biotype \"biotype/transcript\"}}
                                           ^^^^^^^^^^^^^^^^^^^^

should satisfy

  keyword?

**Comment by mgrbyte** [comment]
Fix for #170 will address this in the next release.
