### ISSUE TITLE
Update isn't saved to the database

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#186]
Hi @mgrbyte It seems that updates to a gene isn't saved to the database, even though the API response is 200. Subsequent GET requests see none of the changes, and nothing in the `history` attr either.

The problem can be reproduced on the `develop` branch since today (mar 27th). Thoughts?

![Screen Shot 2019-03-27 at 5 42 06 PM](https://user-images.githubusercontent.com/1753893/55114453-54e4dc00-50b8-11e9-8946-8262ef6d37b3.png)

**Comment by mgrbyte** [comment]
Thanks for the report @sibyl229! A fix for the previous fix wasn't applied properly for update.
