### ISSUE TITLE
Does /api/recent/gene require auth now?

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#194]
Just making sure the change is intentional, because the endpoint didn't require authentication yesterday. 

It's slightly easier to work with the public endpoint. Also it might become useful if we plan to have some UI functions that doesn't require login. 

But it's also not a huge deal either way, if you have performance reasons to keep the endpoint behind login.

**Comment by mgrbyte** [comment]
Change was intentional; but we should discuss more :+1:

**Comment by sibyl229** [comment]
@mgrbyte Good to know. Thanks! Let's leave the issue open until we chat as a reminder.

**Comment by sibyl229** [comment]
Agreed on requiring Auth for /api/recent , and other endpoints going forward.
