### ISSUE TITLE
Ability to clear/unset cgc-name when updating a gene 

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/names#204]
Curators need the ability to clear/unset a cgc-name from a gene.

-. Normally, this should only be/is done for `cloned` genes. 
- Normally, gene names should not be permitted to be blank/empty.
- An endpoint exists for the purpose of explictly removing a cgc-name:  `DELETE /api/gene/cgc-name`
- Consider adding an "X" button next to the cgc-name box to that invokes the above endpoint.

Questions
- should the server refuse to complete the request if no other names are set? (e.g attempting this on an uncloned gene would result in an "anonymous" gene (just id and species).

**Comment by sibyl229** [comment]
I think the interaction (of using a button to remove the name) doesn't feel as natural as clearing the input from the form. This seems to be backend data validation problem. It seems weird to have it affect the interaction and UI in this way.

**Comment by mgrbyte** [comment]
@sibyl229 Agree that it doesn't seem intuitive.
The issue is that the b/end app needs to be able distinguish between a user clearing the cgc-name,
or not entering one.

`gene/cgc-name` cannot be in the payload and be empty string (validation error)

It would be possible to set  `gene/cgc-name` to `nil/null` and then the server could treat that as a request to clear any existing stored `:gene/cgc-name` value for the associated gene.

This is for cgc-names only; it's currently not permitted to clear/blank/remove a sequence-name (as that would leave a form of gene stored that's neither cloned nor uncloned).

Hence my rationale for having a separate endpoint for removing a gene's cgc-name.

Happy to change it up or discuss any alternate ideas.

**Comment by mgrbyte** [comment]
@sibyl229 So, I've spoken with @Paul-Davis  @gw3 amd @epaule...
consensus is that there isn't a requirement for being able to remove/clear cgc-names via the UI.
They do need to be able to do this, but they're happy to do it via the scripts/rest API directly.
So will close this (nothing for you to do).

Apologies for the noise.

**Comment by sibyl229** [comment]
@mgrbyte I see. Thanks for the clarification! If the requirement changes, I'm happy to discuss this further.
