### ISSUE TITLE
Ability to add remark/reason for adding new/editing variations

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/names#219]
When creating or editing a variation, allow the user to enter a reason/remark (ala gene).

**Comment by sibyl229** [comment]
@mgrbyte what is the attribute name for this field?

**Comment by mgrbyte** [comment]
Reason/remark should be the same as for gene: `provenance/why`

**Comment by mgrbyte** [comment]
Apologies @sibyl229 , this feature is already present (!) , I just didn't notice that the reason field doesn't appear until you fill in something in the form (works same way for gene too), so closing.
