### ISSUE TITLE
Unable to render site

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/names#225]
@sibyl229 Tested #224 locally and was all good, but when deploying via jar file/docker, (something) causes the site not to be rendered due to a js file having html in it.

![names-js-error](https://user-images.githubusercontent.com/3185091/58798646-0e9d8300-85fb-11e9-9d74-44893eb6b739.png)

Any ideas what might cause this? (REST API and swagger /api-docs  is working fine)

**Comment by sibyl229** [comment]
Hi Matt, that's interesting. Could you check something for me? As I am at a
conference and can't get access their internet on my computer. I might be a
few days before I get internet.

The screenshot you showed me seems to indicate that the 2.xxxxx.chunk.js is
an html file. That isn't the case in my client/build/static/js/ directory.
Could you try run `yarn install` and `yarn run build` and send me the
content of the file above?

Thanks!

**Comment by sibyl229** [comment]
Hi @mgrbyte actually, I can reproduce what you got. And what's interesting is that the static assets in `client/build/static` are fine, but they are not what's being served by ring server. Any chance the ring handler is modified lately? Maybe a new middleware is added for the authorization?
