### ISSUE TITLE
Conditionally show name field depending on entity config

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/names#249]

**Comment by sibyl229** [comment]
@mgrbyte Is there a server portion to his feature?

Can you confirm whether the name field is optional or is not allowed for these types? Thanks!

**Comment by mgrbyte** [comment]
The `GET /api/entity` endpoint should return a "named? -> boolean" key/value for each entity in the system - if the value is false, then the name is not required when submitting new (or updating existing) entities. I've opened #264 which will address this when fixed.

**Comment by sibyl229** [comment]
I changed the Name field label to "Name (optional)", when `name?` is false.

Note there isn't any UI sided form validation, so nothing is done in terms of that.
