### ISSUE TITLE
Ensure event date is stored in UTC time

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/names#255]

**Comment by mgrbyte** [comment]
@sibyl229 - Are there any places in the UI where a timestamp is sent to the server?
Off hand, I think the only endpoints that might do are `/api/recent`, and any endpoint `"when"` values submitted as provenance.

**Comment by sibyl229** [comment]
@mgrbyte I don't think the UI send any timestamp **To the server**, at least not intentionally. I imagine all the provenance/when (ie the time recorded) is server derived.

The UI does receive timestamp from the server for display purpose though.

**Comment by mgrbyte** [comment]
Good to know :) The server should always present (and store) times in UTC; so in the API responses (e.g provenance); this pertains to the event time only (the `"when"` value in provenance).

**Comment by mgrbyte** [comment]
Closing as this seems to be catered for.
