### ISSUE TITLE
"why" property not returned for merge and split event

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#260]
It works on other event types such as create and kill. The problem seems to only affect the merge and split event types.

Here is an example:
The call the split:
![Screen Shot 2019-11-01 at 4 19 00 PM](https://user-images.githubusercontent.com/1753893/68053933-8dd6d600-fcc3-11e9-8a4b-5c687a53c061.png)
The next fetch for the gene:
![Screen Shot 2019-11-01 at 4 21 19 PM](https://user-images.githubusercontent.com/1753893/68054030-c4acec00-fcc3-11e9-9ae5-280b29b347a6.png)

**Comment by mgrbyte** [comment]
Hi @sibyl229 - all keys in request and response payloads should now be unqualified, so think if you use `"why"` instead of `"provenace/why"` this should work.
