### ISSUE TITLE
gene split biotype

### ISSUE THREAD

**Issue by epaule** [WormBase/names#266]
I think it would be nice if the biotype could default to the gene that is being split, or maybe protein coding if you don't want to look it up.

**Comment by mgrbyte** [comment]
@epaule 's issue in #266  -
@sibyl229  - Apparently it's frequently the case when splitting genes that the product gene biotype is the same as the source. Can this be set as the default in split dialog?

**Comment by sibyl229** [comment]
Yup, it can be set to the current biotype. I previously left it unset, because I didn't know whether it was a reasonable assumption. Now I know. PR is created.
