### ISSUE TITLE
Remove yarn

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#277]
@mgrbyte I'm **thinking** of removing `yarn` as part of the UI tool chain. Any thoughts on this?

If we remove yarn, most of the commands that you previously run with `yarn` will need to be `npm`.  

The main reason yarn was included was for its speed at installing packages and the ability to reproduce the dependency installation. The difference in speed is minimal now, and npm is now supporting reproducible dependencies through package-lock.json.

Using yarn also makes it tricker to work with `nvm`, requiring the additional step of `npm install -g yarn`.

**Comment by mgrbyte** [comment]
@sibyl229 less is more, go for it :+1:
