### ISSUE TITLE
Names UI session bug/login issue on page refresh

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/names#282]
Hi,

I guess this is the best place to add bugs noticed in the names.wormbase.org UI

It seems that a page refresh or if you alter the url you get presented with a login page even though you have an active session. If you login again you get the google authentication pop-up but the box is empty and then vanishes. If you refresh the page sometimes you get back to your session, but not always

Here is a screen cast https://app.box.com/s/fjq8a9sf945xss5q7dzcic7xx59qfxn8

Low priority bug as it's user resolvable, but something to poilish the service??!

**Comment by sibyl229** [comment]
@Paul-Davis Good point! I have a guess about what is happening. 

Some background here. Login in Name Service involves 2 steps: 
1) the UI authenticating with Google resulting in a token being fetched, and 
2) the UI sends the token to the API, the API verify the token and authorize requests based on the token included in the header.

Previously the UI consider to be logged in, once Step 1 succeeds. But I guess there are reasons for Step 2 to fail, and the error message should be communicated back to the user. I created a pull request to verify Step 2.

**Comment by mgrbyte** [comment]
@Paul-Davis please can you test this at your convenience (I've deployed Sibyl's fix above).

**Comment by sibyl229** [comment]
@Paul-Davis @mgrbyte please hold on about testing. It seems that the javascript didn't build correctly on name server. Let @mgrbyte and I talk discuss this first.

Here is the hash for the js when I built on the latest of master branch:
```
build/static/js/2.2bc34b63.chunk.js
build/static/js/main.b1dd6d84.chunk.js
```

**Comment by mgrbyte** [comment]
Believe this is now fixed, closing.
