### ISSUE TITLE
How to retrieve from the API information about the current login user

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#283]
It seems that the Person GET endpoint requires the WBPerson ID to retrieve information about a person. But the WBPerson ID isn't available to the UI, only the id_token.

The use case for this are:
1) to verify is a user is indeed authorized by the backend API
2) display the relevant information on profile page

**Comment by mgrbyte** [comment]
You can use the currently authenticated user's email in place of the WBPersonID.
That should be available to the UI via the Google API response.

**Comment by sibyl229** [comment]
That's great! I will use that. Thanks!
