### ISSUE TITLE
Shall I rename the "Reason" box "Comment", if that's how it's been used?

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#285]
@Paul-Davis @mgrbyte I seem to caused confusion by labelling the text box "Reason". Is "Comment" a better description of its purpose?

**Comment by mgrbyte** [comment]
@sibyl229 I think either is fine, it's intent is to provide the user to place a remark in the audit trail.
Just asked @gw3 and he suggested "reason", so let's leave as-is :+1:
