### ISSUE TITLE
Empty field validation

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/names#293]
Hi @sibyl229 ,
not sure whether you consider the following a UI or server side issue:

Create gene:
 - add CGC-name
 - select species
 - start typing in the Sequence name field, then blank
 - submit

**Comment by sibyl229** [comment]
@mgrbyte when the API response returns a standardized error, the UI has a universal way of handling it. But in this case, it seems that it's a 500 error with response `{"type":"unknown-exception","class":"java.lang.ClassCastException"}`, which isn't compatible with the format the UI expects. Is there a way for the API response to produce the same structure for both the 500 error and the checked errors?

Attached below the request to reproduce the 500 error.
![Screen Shot 2020-02-10 at 11 52 54 AM](https://user-images.githubusercontent.com/1753893/74171071-ee977800-4bfb-11ea-97eb-ee91deacc4ce.png)

**Comment by mgrbyte** [comment]
> @mgrbyte when the API response returns a standardized error, the UI has a universal way of handling it. But in this case, it seems that it's a 500 error with response `{"type":"unknown-exception","class":"java.lang.ClassCastException"}`, which isn't compatible with the format the UI expects. Is there a way for the API response to produce the same structure for both the 500 error and the checked errors?
> 
> Attached below the request to reproduce the 500 error.
> ![Screen Shot 2020-02-10 at 11 52 54 AM](https://user-images.githubusercontent.com/1753893/74171071-ee977800-4bfb-11ea-97eb-ee91deacc4ce.png)

That's a bug, I hadn't spotted (thanks!) it was a 500, will fix.

**Comment by mgrbyte** [comment]
Hi @sibyl229 , 
I've been unable to reproduce the 500 error (just tested on current [master](5563470777d1abf5e086955890d586365436896d).

I've added a screenshot of the result of following the steps as per the OP. 

![wb-names_issue_293_reproduction](https://user-images.githubusercontent.com/3185091/74954987-e0b3d500-53fb-11ea-82ba-0d1697241e35.png)

**Comment by sibyl229** [comment]
Hi @mgrbyte it works fine for me locally too. Do you think the UI should trim the input?

**Comment by mgrbyte** [comment]
@sibyl229 What's going on is the server code expects name fields to have valid data (if supplied).
If the sequence-name field is not filled in, it's not sent to the server - so creating an uncloned gene works. Ideally, the UI could remove the entry in payload it sends for cgc-name or sequence-name if blank.

**Comment by mgrbyte** [comment]
@sibyl229 Had a go at implementing this server-side in 196bf6c - I've not finished manual testing yet, but automated test suite is passing.

**Comment by mgrbyte** [comment]
Fixed in latest release 1.2.2
