### ISSUE TITLE
Consider auto-recovery based on Health Check URL

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#294]
I wonder if some features of beanstalk could help up reduce the downtime of name server.

**Comment by mgrbyte** [comment]
I'm in favour of using AWS alarms to proactively respond to failure events.
Identifying the events/conditions is proving tricky.

**Comment by sibyl229** [comment]
I agree with responding proactively to failure events. 

In addition, if we can identify the exact component that failed and if we can restart or replace that component, then maybe it's okay to leave the exact nature of the failure a mystery. Instead, we automate the restart/replace of the failed component, by responding to failure event triggered by CloudWatch.

**Comment by mgrbyte** [comment]
In the case of `:db.error/transactor-unavailable` - the service auto-recovers, it just takes time (up to 11 seconds given the default configuration) for a datomic peer to [fail-over](https://docs.datomic.com/on-prem/ha.html#peer-recovery-time) to the standby transactor. 

The other error that I've seen (but not for some time) is when the peer (web app) loses connection to the database and doesn't recover. This is one I think we might be able to utilise alarms for - this far I've been unable to reproduce it, and hasn't recurred on the service for some time.

[connection-pool-error.log](https://github.com/WormBase/names/files/4237132/connection-pool-error.log)

**Comment by mgrbyte** [comment]
In the `:db.error/transactor-unavailable` case , I'm currently attempting to figure out how to configure an alarm for when the thresholds are exceeded in CloudWatch - using the `HeartbeatMsec` and `HeartMonitorMsec` metrics, in the first instance to discover how often the fail-over condition (2 consecutive heartbeats missed) is exceeded.

**Comment by mluypaert** [comment]
In meeting with Magdalena, this didn't seem to be an real issue anymore (more downtime is caused by update deployment rather than system failure).
