### ISSUE TITLE
Missing merge events in history (recent API)

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/names#306]
Reported by @gw3 
 
When a merge causes no changes to the "merged-into"  gene (the gene that "stays alive") the entry showing the live gene with corresponding "merges" <other-gene-id> entry is missing  from the history view (as listed by /api/recent/gene/web)

this is caused by no data changing (a provenance-only transaction).
The only example that can cause this is merging two uncloned genes, specifying no changes (e.g biotype) in the merge data.

Currently, the sequence-name for the gene to be killed is "lost" and the "merged-into" gene.

Solution:
Reverse the assignment to :gene/merges; i.e add the from-id to the into gene in wormbase.ids,core, since the from-gene will always have data changed (status = dead)
Factor the recent app endpoints to handle redundant transactions (transaction that have no associated entity id, due to nothing being changed)

**Comment by Paul-Davis** [comment]
Not sure which gene @gw3 reported this on, but the 2 I sent him were standard(ish) looking gene mergers, full audit trail from a "User" perspective.

Standard merge with no cgc names involved.
https://names.wormbase.org/gene/id/WBGene00018299 dead and merged into has unique sequence name
https://names.wormbase.org/gene/id/WBGene00018300 live has unique sequence name

Both genes had a CGC name so cgc_name removed from the gene to die and then the merge took place
https://names.wormbase.org/gene/id/WBGene00007930 dead and merged into has unique sequence name
https://names.wormbase.org/gene/id/WBGene00007929 live has unique sequence

Neither of these are returned/processed by the recent_changes.pl script

WBGene00007930_WBGene00007929 merged on the 9th
perl $CVS_DIR/GENEACE/recent_changes.pl -from 2020-04-08 -until 2020-04-10 -outfile ~/DATABASES/geneace/NAMEDB_Files/NewNS_dataWBGene00007930_WBGene00007929.ace_test  

WBGene00018299_WBGene00018300 merged on 05-05-2020
perl $CVS_DIR/GENEACE/recent_changes.pl -from 2020-05-04 -until 2020-05-06 -outfile ~/DATABASES/geneace/NAMEDB_Files/NewNS_dataWBGene00018299_WBGene00018300.ace_test

Actually looks like there is debug code now:

WBGene00007930_WBGene00007929
Extracting data from dates from 2020-04-08 until 2020-04-10, inclusive
gene what = merge-genes statusdeadmergesWBGene00007929

WBGene00018299_WBGene00018300
Extracting data from dates from 2020-05-04 until 2020-05-06, inclusive
gene what = merge-genes mergesWBGene00018300statusdead
