### ISSUE TITLE
REST API gene merge event labels are reversed for recent merges

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/names#308]
Due to the changes made in #306.
events described as "merged into" should be "merged from" and vice-versa.

**Comment by mluypaert** [comment]
As discussed in PR #309, this issue can be closed without further action, as it resulted from an incorrect interpretation of the labels, meaning the current implementation is correct and there is nothing to fix.

**Comment by mluypaert** [comment]
Although the Client seems to be unaffected (which PR #309 aimed to fix), the gene `GET` API endpoint does return incorrect `merged-into` and `merged-from` labels in its output data for genes merged after the code changes introduced in #306.

As the client code was unaffected, the API code should mimic this logic:
* the `dead` gene merged into another gene
* the remaining `live` gene merged (info) from the dead gene

The code should do this gene-status evaluation based on the exact moment-in-time when the actual merge occurred, to prevent genes from getting incorrect merging labels after killing (or resurrecting) them.

**Comment by mluypaert** [comment]
Fixed on `master` branch, code still to be deployed to test and prod environment (combined with some other issues).
