### ISSUE TITLE
Gene unsplit breaks gene information retrieval

### ISSUE THREAD

**Issue by mluypaert** [WormBase/names#315]
Using the unsplit operation (`DELETE` call to the `gene/{identifier}/split/{into-identifier}` API endpoint) breaks the gene information retrieval (`GET` call to `gene/{identifier}` API endpoint) for the split product gene.

The unsplit operation removes some gene attributes (like `:gene/biotype`), which causes the gene information retrieval's output validation to fail.

**Comment by mluypaert** [comment]
Probably related to the same code(block) as #314

**Comment by mluypaert** [comment]
The current unsplit operation makes the following changes to the split product:
* Leaves the `:gene/id` attribute be
* Sets the `:gene/status` attibute to dead
* Removes any other attribute from this entity

This causes the gene-information API output-validation to fail, as it expects more attributes than just `:gene/id` and `:gene/status` to be set. There's three possible ways to fix this issue:
1. Unsplit by reverting any changes made to the attributes of the origin gene and delete all attributes related to the split product (including `:gene/id` and `:gene/status`). This is a true "undo the entire split operation", however this also means you cannot find the split product afterwards, it will only remain visible through the history. (to my opinion, the preferred option)
2. Unsplit by reverting any changes made to the attributes of the origin gene, keep most attributes of the split product, but set it's status to dead. The `:gene/sequence-name` attribute of the split product might need to be removed, if you want to be able to use the same sequence-name for another gene (open for discussion whether that's needed).
3. Change the get-information output validation so it would accept (dead) genes that only have a `:gene/id` and `:gene/status` attribute (and not even a `:gene/species`).

Note: any unsplit operation will **not** reset the `:gene/counter` attribute, as this would always cause problems if a new gene got created after the original split operation (see #314), so the split product's `:gene/id` value (wormbase ID) can never be recycled by other genes.

@gw3 @Paul-Davis we may need to discuss this in order to pick the most suited option, once everyone is back from holidays.

**Comment by Paul-Davis** [comment]
I think leaving the  :gene/sequence-name attribute on the Dead gene is fine, this should hopefully resolve 1). 2) I think not reusing the :gene/sequence-name attribute is fine, I don't think completely removing a mistake is necessary and like we mentioned on the call this AM, we can't remember ever doing this. 3) Hopefully no longer necessary with the proposed change above.
