### ISSUE TITLE
Change history UI error

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/names#318]
Coming from #316 but unrelated??

When looking on the gene record in the NS 
https://names.wormbase.org/gene/id/WBGene00229914

We get an error in the history panel

![History_issue](https://user-images.githubusercontent.com/717707/92009243-230d8580-ed40-11ea-9619-bdef84bc32b4.png)

Low priority but would be good to fix, could be a data or code issue??

**Comment by sibyl229** [comment]
This is probably because the UI doesn't know what to do if the event `what` field is `null`. It probably shouldn't be null?

![Screen Shot 2020-09-02 at 12 21 26 PM](https://user-images.githubusercontent.com/1753893/92009993-4112c000-ed17-11ea-9f1f-461222e43a49.png)

**Comment by Paul-Davis** [comment]
Thanks @sibyl229 yes, this looks like one of those anoying edge cases where noting was stored against the what: field for supressed genes. Is it a simple fix?

**Comment by mluypaert** [comment]
Now deployed to both production and test environments (wormbase-names 1.4.4 and up)
