### ISSUE TITLE
Show human readable error messages in the UI

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#32]

**Comment by mgrbyte** [comment]
Can you detail what's needed from the (server side) api for this?

**Comment by mgrbyte** [comment]
I think what's needed here is [phrase][1] to turn the spec errors into human-readable ones.
The spec error should still be returned in the HTTP error response, but an extra key, say `:user-error` will be supplied.
These need only be implemented for validation messages (40x HTTP responses).

[1]: https://github.com/alexanderkiel/phrase

**Comment by sibyl229** [comment]
@mgrbyte Your solution sounds good to me!

**Comment by mgrbyte** [comment]
All HTTP errors in the `4\d{2}` range should have a `message` key that we could display for the initial release, although this won't be fine grained enough atm, it'll be a good first pass.

Suggest we do that for `0.1` and I'll make sure that validation errors are logged in the interim.

**Comment by sibyl229** [comment]
Sounds good! If we wants to include the spec output permanently, I wonder if it's possible to indent the edn for readability, so it's not all on a single line? I saw this library called rewrite: https://github.com/xsc/rewrite-clj , not sure if it helps in this case.
