### ISSUE TITLE
Relax CGC name regex or allow exception

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/names#322]
cwf-19L1 is a valid C. elegans gene name that I was able to add to the gene  WBGene00017534 via console.

I need to add the same name to the other core species where they are predicted to be the Ortholog

ERROR: Server - WBGene00223673 missing cgc name Bma-cwf-19L1
ERROR: Server - WBGene00058814 missing cgc name Cre-cwf-19L1
ERROR: Server - WBGene00132786 missing cgc name Cjp-cwf-19L1
ERROR: Server - WBGene00280521 missing cgc name Ppa-cwf-19L1
ERROR: Server - WBGene00154314 missing cgc name Cbn-cwf-19L1
ERROR: Server - WBGene00030866 missing cgc name Cbr-cwf-19L1

Unfortunately the regex does not allow me to do this for the above species.....(below is the result of trying to do it using the UI).

cgc-name: Bma-cwf-19L1 Did not match species regular expression pattern.

 ^Bma-[a-z21]{3,4}-[1-9]\d*(\.\d+)?$

I was wondering the following: 

- If there is something in the API to ignore the regex if you know it's an unusual name
- How I was able to do it for elegans and not the other species
- Should we have a database admin only oporation for strange edge cases like this?

P

**Comment by mluypaert** [comment]
In meeting with magdalena and after discussion with @Paul-Davis we decided this issue would be too much effort to fix for its impact. To be revised if problem is hit more frequently
