### ISSUE TITLE
WBM60 strain causes search to fail even though the strain exists.

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/names#324]
I believe that this is caused by the autocomplete "hack"/Edit  where if the search string starts with WB but has less than ?7 characters then the search does not kick in correctly?

WBM60 - WBStrain00040333

The autocomplete work around was put in place to stop returning every Variation/Strain/Gene as the user typed. I thought that this was exclusively for the UI end points but it seems the perl API also uses it?

**Comment by Paul-Davis** [comment]
![WBM60_not_found](https://user-images.githubusercontent.com/717707/109194093-fb4c2700-7790-11eb-825e-09f2e56a0468.png)
![WBM60_found](https://user-images.githubusercontent.com/717707/109194096-fbe4bd80-7790-11eb-928f-d9368fd7852b.png)

**Comment by Paul-Davis** [comment]
Example perl script query:

```
acedb3:cat WBM60.in 
WBM60
 
acedb3: perl $CVS_DIR/GENEACE/show_NS_ids.pl -in WBM60.in -out WBM60.out -debug pad -species elegans -domain Strain
 
acedb3: less WBM60.out
//Cannot find WBM60
```

**Comment by tuli** [comment]
Hello,

I am sure I keep unsubbing from these lists, but I still
occasionally receive emails.

Can someone remove me from the WormBase git repositories once and for all.

Thank you,

Mary Ann

**Comment by Paul-Davis** [comment]
@tuli as it's github you probably need to login and leave all the repos you signed up to as I don't believe anyone in WB can just kick you?

P

**Comment by Paul-Davis** [comment]
@tuli if you go to your profile you can leave the WormBase organisation which will remove you from all WB repos. You can probably resolve it faster for yourself as it's only just gone 3:30AM for Todd and he's the only person who can do it.

**Comment by tuli** [comment]
Thanks.
I am already not part of WormBase, I am part of GigaScience and the ISB. I
have chosen to permanently ignore GeneNames so that should do the trick.

**Comment by mluypaert** [comment]
@Paul-Davis Your guess was correct, search for this particular strain fails because of its resemblance to wormbase IDs (identified by the API as `WB[a-zA-Z]+(\d+)`) and a filter blocking searches for IDs when less than 7 digits are provided. However, this filter is present both in the UI and in the API itself, causing the perl script to fail as well.

FYI: the API returns an error message that indicates this when queried directly:
```bash
$ curl --no-progress-meter -X "GET" -H "Authorization: Token $WB_API_KEY" -H "Accept: application/json" 'https://names.wormbase.org/api/entity/strain?pattern=WBM60' | jq .
{
  "matches": [],
  "message": "Identifier must contain at least 7 digits (received 2)."
}
```

**Comment by mluypaert** [comment]
Fix implemented, searching for WB-ID-like patterns with < 7 digits will now result in the return of exact matches only (with a warning message) by the API, rather than no matches at all. Autocomplete will still not return anything. Release and deployment still to be done, combined with #304

**Comment by mluypaert** [comment]
@sdiamantakis A fix for this has now been deployed to production. Searching for WB-ID-like patterns will now return results when the pattern has an exact match on the database, or if the search pattern has 7 or more digits (like `WBStrain0001234`) in which case it will return partial matches as well. This behavior is implemented identically for both API and UI.

**Comment by sdiamantakis** [comment]
Epic! Thanks @mluypaert !
