### ISSUE TITLE
Provide endpoint for recent activities

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/names#42]
## Proposal

Provide a listing of the the last 2 months' transactions, paginated.
Sorted by `:provenance/when`, most recent first.

*URI*: /api/recent
*Method*: GET
*Params*: page (number), per-page (number)
*Response*:
```clojure
{ :total-pages ... ;; total number of pages in the period (2 months, hard-coded for now)
  :page
  :recent 
  [{:provenance/when ...,
    :provenance/how ...,
    :provenance/who ...,  }, ...][}
```

**Comment by sibyl229** [comment]
Hi @mgrbyte looks good! Can I also get the a count for the total number of items? Probably needs to display it somewhere.

A few questions:
- If there are new events happening while the user paginates through, are request made on the same "database" (in the datomic sense) or on the latest database? I'm not sure which behaviour is more desirable from a user perspective.
- For merge and split event, shall I display the created gene and deleted gene as the Entity and the gene that stays around as the "Related entity"? This seems straight forward, but when compared with the table on gene page (where the _current_ mockup lacks the entity column), it might raise a subtle inconsistency:
    - on the gene directory page, "Related entity" means the gene that stays around, while 
    - on the gene page, "Related entity" means the other entity involved in the event. 
I'm think of including the Entity column in both tables to avoid inconsistency and confusion, even though it might be more verbose. What do you think?

**Comment by mgrbyte** [comment]
Hi @sibyl229 ,
Number of items: :ok: 
new events: 
I think (?) a good first  step for the UI/UX would be a flash notification somewhere that says "hey there are new items", with a link to "show", when the user is interacting with the page. Perhaps a coloured bar pinned to the top of the page?

"Related entity" display: 
Personally, I don't like term "related entity".
I think maybe ditch the related entity column on the "directory" page, since (i _think!_)
the merge and split events will result in both participants being listed in adjacent rows in the table, due to sorting by time.
(except possibly in the *extremely* rare case where two distinct events happen within a

**Comment by sibyl229** [comment]
Hi @mgrbyte 

Number of items: great

New events: sound good! So I imagine if the user choose not to interact with the "load new events", pagination will be based on the same database? And I guess the response for each page would indicate whether there is a newer version of the database, so the UI code can decide whether to show the new events notification?

Related entity:
Maybe we can get curator feedback on this after I have an initial implementation. What would the two adjacent entries look like? Kinda curious if the decision to return two entries for a event is out of consideration for the display or for the data model.

**Comment by mgrbyte** [comment]
New events: continued
yes, this can get a bit tricky!

I _was_ thinking:
 * that a "load new events" action would re-query the api with the same params (i.e page=2&... etc), and the display would update accordingly.
 * Any other the user takes in the UI  should _always_ uses the _current_ db. (i.e not planning on using `asOf` or `since` datomic.api APIs in endpoint handlers. 
   
Think it needs more thought...

**Comment by mgrbyte** [comment]
@sibyl229 Looking to pick this up again soon.

I think we need two views (one for operations done via web and another via scripts/batch api. 
 * scripts
   * individual changes, similar to history view on gene profile
 * batch records
   * one row per batch operation (entity kind, batch identifier, number of affected items, who, why)

**Comment by mgrbyte** [comment]
1st attempt at this done in #171.
