### ISSUE TITLE
SSL cert and domain (names.wormbase.org?)

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/names#46]

**Comment by sibyl229** [comment]
I talked with @tharris about this. The solution we came up with involves having `names.blah.blah` going through the proxy, where the SSL certificate is applied. We will be using a wildcard SSL certificate that we currently use for the WormBase website and some of the subdomains.

Traffic from names.wormbase.org will be proxied to ---- redacted --. So, when we deploy to EB in the future, I think we need to ensure the production deployment uses the same URL (by using the EB feature of swapping URL between two environments).

I will let you know when things are setup.

Questions or thoughts?

**Comment by mgrbyte** [comment]
Nope, sounds good. Might have to add some headers/settings such that auth headers go through correctly, but happy to work with that once we start testing it :+1:

**Comment by tharris** [comment]
Okay, the proxy configuration is in place now. http redirects to https. I redacted the EB and name server hostnames in the original comment above -- maybe don't want to have that public.

Also, note on the swagger interface that it should read WormBase, not Wormbase.

**Comment by sibyl229** [comment]
Great! Thanks @tharris ! 

I edited the typo in the code.
