### ISSUE TITLE
Indicate gene status on "gene profile" page

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/names#48]
Currently, not obvious in UI if gene is live or dead.

Questions: 
  - Do we have some kind of box in the top right with the text "Live", "Dead" or "Suppressed"?
  - Should the background of form greyed out if Dead, slightly lighter greyed out if Suppressed?
  - Should we disable editing of gene when gene status is Suppressed or Dead?
  - Do you prefer a drop down to change the gene status or a button to say "kill" (the later is what is currently implemented)

@Paul-Davis @gw3  @epaule Any thoughts on what you'd prefer to see/have here?

**Comment by sibyl229** [comment]
The UI actually tries to show Live and Dead gene quite distinctly, though it can be made more distinct. Editing is disabled for a Dead gene at the moment.

![screen shot 2018-08-30 at 11 21 10 am](https://user-images.githubusercontent.com/1753893/44861602-d4a3e880-ac46-11e8-97f4-dcbefe2b3a90.png)
![screen shot 2018-08-30 at 11 18 00 am](https://user-images.githubusercontent.com/1753893/44861610-d8376f80-ac46-11e8-8605-8da618791068.png)

Could someone explain what a "Suppressed" gene is? Is there any difference when you work with a Suppressed vs a Dead gene?

Personally, I prefer "Kill" button outside of the form and appears very alarming to minimize chance of accidentally clicking on it.

**Comment by mgrbyte** [comment]
@sibyl229 Sorry, got :confused: when testing... 
Editing/interacting with suppressed gene should be the same as with a live gene.

A gene with the status suppressed is (*usually*) one that has a biotype of `transposable-element-gene` (or `Transposon_in_origin` in the ACeDB WB world). These genes *are* live, but are do not want to be considered for certain types of data-processing, or to be included in the canonical gene set. (Paraphrasing @khowe  here, he can correct me If I've not got that right!)    

Related to this: #20

**Comment by khowe** [comment]
Yes - a "Suppressed" gene is one that is "alive", but we want to hide/exclude from the gene set (for whatever reason).

**Comment by sibyl229** [comment]
Thanks @khowe ! I will start by setting up the UI for suppressed gene with a "Suppressed" badge, but otherwise behave like a regular live gene. We can make changes to it later if needed.

**Comment by sibyl229** [comment]
And thanks @mgrbyte :)

**Comment by mgrbyte** [comment]
Closing this, perhaps we should create a new issue for displaying suppressed genes? Re-open if you'd like to keep it here.

**Comment by sibyl229** [comment]
@mgrbyte It's okay. Don't worry about creating new issues for this. I will re-open it. The discussion here is really helpful.

**Comment by sibyl229** [comment]
@mgrbyte About gene status and transition between them, is this an accurate representation of what we will and will not implement?
![gene status dfa 1](https://user-images.githubusercontent.com/1753893/45234514-f6831800-b2a3-11e8-8b38-39cffb36583a.png)

I forgot what we decided on "un-suppress". Is it post-0.1? And for 0.1 milestone, the way to un-suppress a gene is to kill and resurrect it (an 2-step / non-atomic operation)?

**Comment by mgrbyte** [comment]
Yep, diagram looks right.
and yes to the 2-step kill & resurrect for now to un-suppress (for now) :+1:
