### ISSUE TITLE
Undo a split leaves no trace of the "split-into" ID

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#65]
To reproduce:
- Split a gene (**GeneA**), and let's call the gene created from this split event **GeneX**
- Observe that the page for Gene X exists
- Undo the split
- Visit the GeneX page again
- Observe PageNotFound error (Expected: a Dead gene page? or some indication that it existed before?)

**Comment by mgrbyte** [comment]
@sibyl229 Will chat to you about this one (just been talking with @Paul-Davis about it)

**Comment by sibyl229** [comment]
Close for now. Will open new issues once we are ready to work on undo.
