### ISSUE TITLE
"Undo-able" events / has an event already been undone

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#66]
A split or a merge event can only be undone once (I think?). But the UI will always display an Undo button, because it can't tell from the history JSON if any particular event has already been undone. That leads to failed undos that might be preventable.

So is there a way to derive information on whether an event is undoable, and have that in the JOSN?

**Comment by mgrbyte** [comment]
@sibyl229 Hi, you're quite right. Having arbitrary undo against historical events is very complex...
Will talk with you about this at the same time as discussing #65.

**Comment by sibyl229** [comment]
Close for now. Will open new issues once we are ready to work on undo.
