### ISSUE TITLE
display of gene biotypes

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/names#69]
biotypes in the system are a high-level categorisation of the corresponding gene in the main WormBase db.
In the main WormBase db, these biotypes are actually modelled using [SO][1] terms.
As such, curators want to see those terms as the "biotype" in the names service.

So, for the simple set that we're using, these are the following labels and corresponding SO acessions:
`transcript` [SO:0000673][2]
`pseudogene` [SO:0000336][3]
`CDS` [SO:0000316][4]
`transposable_element_gene` [SO:0000111][5]

Change: use labels above verbatim in the display wherever we present biotype.

[1]: http://www.sequenceontology.org/miso
[2]: http://www.sequenceontology.org/browser/current_svn/term/SO:0000673
[3]: http://www.sequenceontology.org/browser/current_svn/term/SO:0000336
[4]: http://www.sequenceontology.org/browser/current_svn/term/SO:0000316
[5]: http://www.sequenceontology.org/browser/current_svn/term/SO:0000111

**Comment by sibyl229** [comment]
@mgrbyte Just to confirm here, should the ajax call still send the biotype as keywords, such as `biotype/transcript`?

**Comment by mgrbyte** [comment]
yes, that's correct.
biotype/transposable-element-gene not biotype/transposon tho

**Comment by sibyl229** [comment]
The PR #74 currently implements this solution. Is this what you are looking for?
![screen shot 2018-09-06 at 1 15 59 pm](https://user-images.githubusercontent.com/1753893/45173750-1ac4f300-b1d7-11e8-92c6-71d656cd1d44.png)
![screen shot 2018-09-06 at 1 16 20 pm](https://user-images.githubusercontent.com/1753893/45173751-1ac4f300-b1d7-11e8-8779-51dff2bd347e.png)
