### ISSUE TITLE
Show details of on an edit change in a gene's history listing

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/names#78]
Where a gene's event  history  row contains an "update gene" (`:event/update-gene`) , provide a pop up box showing the details of the change.

This could be a simple table, e:g:

| Attribute | Old Value |
|-------------|--------------|
| CGC name | "old-name1" |
| Biotype  | old/bt |
| Sequence name | SOMEOLDSEQNAME |

The back-end will need to change to provide this change information.

**Comment by mgrbyte** [comment]
@sibyl229 the table in the post above, perhaps with different headings?) is what I was thinking of "popping up" when clicking on a button in a "gene update" row in the history on gene profile.
Perhaps easiest thing is to make "update-gene" a "link" which will pop that table up as a div (perhaps to the right of the main form w/a close button?)

**Comment by sibyl229** [comment]
Hi @mgrbyte Would it be possible to include the "new values" in the json response, to populate a table like this one?

| Attribute changed | Old Value | New Value
|-------------|--------------|------------|
| CGC name | "old-name1" | "new-name" |
| Biotype  | old/bt | new/bt |
| Sequence name | SOMEOLDSEQNAME | SOMENEWSEQNAME |

I might start by embedding the attribute change table in existing table. (So a nested table). The rationale is to save users a few clicks. We will figure something out if page looks too crowded.

**Comment by mgrbyte** [comment]
> I might start by embedding the attribute change table in existing table. (So a nested table). The rationale is to save users a few clicks. We will figure something out if page looks too crowded.

even better :+1:

**Comment by mgrbyte** [comment]
@sibyl229 I think the changes are _already_ is doing this: added == true = new value, added == false, old value
