### ISSUE TITLE
Error when killing suppressed gene

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#99]
![screen shot 2018-09-25 at 6 37 58 pm](https://user-images.githubusercontent.com/1753893/46047243-45c5a700-c0f2-11e8-855a-575bf7cca320.png)

**Comment by mgrbyte** [comment]
@sibyl229 This is the correct error for trying to kill a suppressed gene (see also diagram on #48)
Can we hide the kill button on the page when the gene is suppressed?

**Comment by sibyl229** [comment]
@mgrbyte I thought killing a suppressed gene and then resurrecting it is the only way to un-suppress a gene. If we don't allow killing a suppressed gene, then we'd have to have the un-suppress functionality. Is that what we are gonna do?

**Comment by mgrbyte** [comment]
@sibyl229 You're quite right, fix incoming.
